//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalleMarketiVeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class müsteriler
    {
        public string MusteriAdi { get; set; }
        public string MusteriKodu { get; set; }
        public string SatinAldigiUrunFiyat { get; set; }
        public string OdedigiMiktar { get; set; }
        public string SatinAldigiTarih { get; set; }
        public string Borc { get; set; }
        public string MusteriAdresi { get; set; }
        public string OdemeYaptigiTarih { get; set; }
        public string SatinAldigiUrunKodu { get; set; }
    }
}
