//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalleMarketiVeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class saticilar
    {
        public string SaticiKullaniciAdi { get; set; }
        public string SaticiSifre { get; set; }
    }
}
