//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalleMarketiVeriTabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MahalleMarketiVeriTabaniEntities2 : DbContext
    {
        public MahalleMarketiVeriTabaniEntities2()
            : base("name=MahalleMarketiVeriTabaniEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<müsteriler> müsteriler { get; set; }
        public virtual DbSet<ürünler> ürünler { get; set; }
        public virtual DbSet<saticilar> saticilar { get; set; }
    }
}
