//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalleMarketiVeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class ürünler
    {
        public string TedarikciFirmaAdi { get; set; }
        public string TedarikciFirmaKodu { get; set; }
        public string UrunKodu { get; set; }
        public string UlkeKodu { get; set; }
        public string IrsaliyeNumarasi { get; set; }
        public string GelisFiyati { get; set; }
        public string Miktari { get; set; }
        public string BarkodNumarasi { get; set; }
        public System.DateTime GelisTarihi { get; set; }
    }
}
